### PR TITLE
Preset scrolling fix + more early HUD updates

### PR DESCRIPTION
**Pull request by InsaneFirebat**
Just a couple more places to update the HUD early: Ceres escape elevator and facing forward on the ship. The ship update runs anytime you press down to go in the ship, not just the escape. Ceres elevator didn't need a separate address for PAL.

### CODE REVIEW

**Comment by InsaneFirebat** [comment]
I forgot to change the overwritten JSL address for PAL. Fixed now.

**Comment by InsaneFirebat** [comment]
I've got a fix for the janky scrolling when loading Phantoon presets (among others) that I'd like to include in this pull. Just needs a bit more testing.

**Comment by InsaneFirebat** [comment]
The scrolling fix first checks the 5th scroll slot to see if it's red (zero) and changes it to blue if so. This fixes a few different presets including Phantoon, GGG, and Aqueduct. It then checks for certain rooms that need a separate or addition fix. These fixes can be found in the door asm leading into the spot with a bad scroll.

**Comment by InsaneFirebat** [comment]
This next commit resets the room timers when starting a new game in Ceres. Time spent in the title menus was included in the room times prior to this change. The hijack is right before the gamestate is incremented from 7 to 8.

Acid Chozo room (before GT) added to preset_scroll_fixes.

**Review by UNHchabo — APPROVED** [review]

**Pull request merged**
