### PR TITLE
Improvements to existing presets

### PR DESCRIPTION
**Pull request by InsaneFirebat**
Improvements to PRKD, KPDR 21%, and GT Classic presets.
Add blue suit to various Terminator presets for breaking blocks
Rename main menu option to "Category Presets"

### CODE REVIEW

**Comment by idlechild** [comment]
So... is this in draft state because you are still working on it?  Or is this ready to merge in?

Presets look complicated to me, I'm trusting you did it right :-)

**Comment by InsaneFirebat** [comment]
It could be merged now if it's wanted. One of the categories included in this pull is already in the practice rom, created by ShinyZeni. I'm not a runner of that category (PRKD) so I wanted to give it some time for testers to send feedback and make sure it was a solid improvement over the original.

I posted it as a draft thinking it wouldn't be visible yet. I was wrong :)

**Comment by idlechild** [comment]
I will be ready to make an unrelated pull request soon, wondering if I should wait for this one to go through first.

**Comment by InsaneFirebat** [comment]
I always wonder how GitHub will handle merging changes. Never tried it myself. This should be an easy one to figure out, since I'm only making a minor change in mainmenu.asm and the rest is in the preset files. I don't mind fixing up my pull if yours goes through first.

**Comment by idlechild** [comment]
Merging will be easy, just don't forget to change your version number if I
end up taking 2.1.2

**Comment by InsaneFirebat** [comment]
This one is ready for review again. Sorry for the delay.

**Comment by InsaneFirebat** [comment]
The changelog on this pull is full of irrelevant junk from working on this over a long period of time and merging in changes from other commits. I'd like to close this pull and replace it with a new one from a fresh branch to clean out the history and make it easier to review.

**Pull request closed without merging**
